import type { EjercicioDisciplina } from "@/lib/tecnica/tipos";

/**
 * CrossFit — los movimientos de verdad, por nivel.
 *
 * La primera versión de esta biblioteca tenía cuatro fichas genéricas y ningún
 * movimiento real: ni clean, ni jerk, ni box jump. Un atleta de CrossFit abre
 * la biblioteca buscando **el movimiento que le tocó en el WOD**, y si no está,
 * la biblioteca no sirve.
 *
 * El orden es el del método: primero los patrones que sostienen todo
 * (sentadilla, bisagra, empuje), después los movimientos completos, y al final
 * las variantes cíclicas que solo tienen sentido cuando la técnica ya aguanta
 * la fatiga.
 */
export const CROSSFIT: EjercicioDisciplina[] = [
  // -- Fundamentos -----------------------------------------------------------
  {
    id: "air_squat",
    nombre: "Sentadilla al aire",
    nivel: "PRINCIPIANTE",
    categoria: "Fundamentos",
    como: "Pies al ancho de hombros, cadera atrás y abajo hasta pasar la paralela, tronco firme y talones pegados al piso.",
    para: "Es el patrón que aparece en más de la mitad de los WOD. Si no está limpio aquí, con barra encima está peor.",
    ojo: "Talón que se levanta o rodilla que se mete. Si pasa, trabaja movilidad de tobillo antes de sumar carga.",
  },
  {
    id: "deadlift",
    nombre: "Peso muerto",
    nivel: "PRINCIPIANTE",
    categoria: "Fundamentos",
    como: "Barra pegada a la espinilla, cadera arriba de la rodilla, espalda neutra. Empuja el piso y cierra cadera arriba.",
    para: "El patrón de bisagra más cargado del deporte y la base del clean y del snatch.",
    ojo: "Lumbar redondeada al despegar. Es la lesión clásica del WOD con muchas repeticiones: cuando la espalda se redondea, ese fue el último set válido.",
  },
  {
    id: "front_squat",
    nombre: "Sentadilla frontal",
    nivel: "PRINCIPIANTE",
    categoria: "Fundamentos",
    como: "Barra en los deltoides con codos altos, agarre suelto de dedos, tronco vertical.",
    para: "Es la posición de recepción del clean y la base del thruster. Sin ella, el clean se queda a medias.",
    ojo: "Codos que caen: la barra rueda al frente y la espalda paga la diferencia.",
  },
  {
    id: "strict_press",
    nombre: "Press estricto",
    nivel: "PRINCIPIANTE",
    categoria: "Fundamentos",
    como: "Barra al frente de los hombros, glúteo y abdomen apretados, empuja vertical y mete la cabeza al pasar la barra.",
    para: "El empuje vertical limpio del que salen el push press y el jerk.",
    ojo: "Arquear la espalda para sacar el peso. Si hay que arquear, sobra peso.",
  },
  {
    id: "burpee",
    nombre: "Burpee",
    nivel: "PRINCIPIANTE",
    categoria: "Acondicionamiento",
    como: "Del pie al piso con pecho y muslos abajo, vuelve de un salto y salta con las manos arriba.",
    para: "El movimiento más democrático del deporte: no necesita nada y sube el pulso más rápido que cualquier otro.",
    ojo: "Acelerar de más las primeras diez. En un WOD largo, el burpee se hace a ritmo constante o te come.",
  },
  {
    id: "box_jump",
    nombre: "Box jump",
    nivel: "PRINCIPIANTE",
    categoria: "Potencia",
    como: "Salto con los dos pies a un cajón, aterriza con la cadera flexionada y extiende arriba. Baja caminando o de salto según el nivel.",
    para: "Potencia de tren inferior y aterrizaje, que es lo que el gimnasio de pesas no entrena.",
    ojo: "Rebotar al bajar cuando ya hay fatiga. El rasguño de espinilla es la lesión más común del box: si dudas, baja caminando.",
  },
  {
    id: "wall_ball",
    nombre: "Wall ball",
    nivel: "PRINCIPIANTE",
    categoria: "Acondicionamiento",
    como: "Sentadilla completa con el balón al pecho y lánzalo al objetivo extendiendo cadera; recíbelo y baja en el mismo movimiento.",
    para: "Junta sentadilla y empuje en un ciclo continuo: es el que mide de verdad la capacidad de trabajo.",
    ojo: "Cortar la sentadilla cuando cansa. Si el WOD pide profundidad, la repetición sin profundidad no cuenta.",
  },
  {
    id: "kb_swing",
    nombre: "Kettlebell swing",
    nivel: "PRINCIPIANTE",
    categoria: "Fundamentos",
    como: "Bisagra de cadera —no sentadilla—, la pesa pasa alta entre las piernas y sube por el impulso de la cadera.",
    para: "Enseña el patrón de bisagra explosivo con menos riesgo que la barra.",
    ojo: "Levantar con los brazos y ponerse en cuclillas. Ahí no trabaja la cadena posterior, que es todo el punto.",
  },
  {
    id: "row",
    nombre: "Remo",
    nivel: "PRINCIPIANTE",
    categoria: "Acondicionamiento",
    como: "Empuje de piernas primero, después cadera y al final brazos. Al volver, el orden se invierte.",
    para: "El monitor más honesto del gimnasio: el ritmo se mide en tiempo por 500 m y no miente.",
    ojo: "Tirar con los brazos desde el inicio. El 60 % del empuje viene de la pierna.",
  },

  // -- Intermedio: los movimientos completos ---------------------------------
  {
    id: "power_clean",
    nombre: "Clean (cargada)",
    nivel: "INTERMEDIO",
    categoria: "Levantamiento",
    como: "Primer tirón lento hasta la rodilla, segundo tirón explosivo con extensión de cadera, y recibe la barra en los hombros con codos altos.",
    para: "Es el movimiento que lleva el peso del piso al hombro y aparece en la mitad de los WOD con barra.",
    ojo: "Tirar con los brazos antes de extender la cadera. La barra sube por la cadera; los brazos solo la guían.",
  },
  {
    id: "push_press",
    nombre: "Push press",
    nivel: "INTERMEDIO",
    categoria: "Levantamiento",
    como: "Flexión corta de rodilla —un dip de dos dedos—, extiende y usa ese impulso para mandar la barra arriba.",
    para: "Mueve más peso que el press estricto y enseña la coordinación del jerk.",
    ojo: "Bajar demasiado en el dip. Es un impulso, no una sentadilla.",
  },
  {
    id: "push_jerk",
    nombre: "Push jerk",
    nivel: "INTERMEDIO",
    categoria: "Levantamiento",
    como: "Dip, extensión y una segunda flexión para meterte debajo de la barra; recíbela con brazos bloqueados y sube.",
    para: "Es cómo se mueve peso por encima de la cabeza cuando el press estricto ya no alcanza.",
    ojo: "Recibir con los codos suaves. La barra se bloquea arriba y después se estabiliza, no al revés.",
  },
  {
    id: "clean_and_jerk",
    nombre: "Clean and jerk",
    nivel: "INTERMEDIO",
    categoria: "Levantamiento",
    como: "Clean completo hasta los hombros, reacomoda el agarre y la respiración, y de ahí el jerk arriba.",
    para: "El levantamiento de más carga total del deporte: es dos movimientos con una pausa deliberada en medio.",
    ojo: "Encadenarlos sin respirar. La pausa en el hombro no es descanso, es parte de la técnica.",
  },
  {
    id: "thruster",
    nombre: "Thruster",
    nivel: "INTERMEDIO",
    categoria: "Levantamiento",
    como: "Sentadilla frontal completa y, sin pausa, empuje arriba usando el impulso de la subida.",
    para: "El movimiento más duro por unidad de tiempo del deporte —Fran son 45 de estos con dominadas—.",
    ojo: "Separar la sentadilla del empuje. El thruster es un solo movimiento; partirlo cuesta el doble de energía.",
  },
  {
    id: "toes_to_bar",
    nombre: "Toes to bar",
    nivel: "INTERMEDIO",
    categoria: "Gimnásticos",
    como: "Colgado de la barra, balanceo controlado y lleva los pies a tocar la barra manteniendo los brazos largos.",
    para: "Core y agarre a la vez, en el patrón que el WOD pide con más repeticiones.",
    ojo: "Balancearse sin ritmo. El kipping es un péndulo: si peleas contra él, se acaba el agarre en diez repeticiones.",
  },
  {
    id: "pull_up_kipping",
    nombre: "Dominada con kipping",
    nivel: "INTERMEDIO",
    categoria: "Gimnásticos",
    como: "Arco y hueco alternados para generar impulso, y tira cuando la cadera empuja hacia arriba.",
    para: "Permite muchas más repeticiones que la estricta, que es lo que el formato del WOD pide.",
    ojo: "Aprenderla sin tener antes 5 dominadas estrictas. El hombro paga el atajo.",
  },
  {
    id: "double_under",
    nombre: "Double under",
    nivel: "INTERMEDIO",
    categoria: "Acondicionamiento",
    como: "Salto de cuerda con dos pasadas por salto, muñeca rápida y codos pegados al cuerpo.",
    para: "Sube el pulso muchísimo en poco espacio y aparece en decenas de WOD clásicos.",
    ojo: "Saltar más alto para que quepan dos vueltas. La velocidad sale de la muñeca, no de la altura.",
  },
  {
    id: "overhead_squat",
    nombre: "Sentadilla por encima de la cabeza",
    nivel: "INTERMEDIO",
    categoria: "Fundamentos",
    como: "Barra bloqueada arriba y ligeramente atrás, hombros activos, sentadilla completa sin que la barra se vaya al frente.",
    para: "Es el examen de movilidad del deporte y la posición de recepción del snatch.",
    ojo: "Forzarla sin movilidad de hombro y de tobillo. Aquí no se compensa con fuerza: o hay rango o no lo hay.",
  },
  {
    id: "wall_walk",
    nombre: "Wall walk",
    nivel: "INTERMEDIO",
    categoria: "Gimnásticos",
    como: "De plancha con los pies en la pared, camina con las manos hacia la pared hasta quedar casi vertical, y regresa.",
    para: "Fuerza de hombro en posición invertida sin necesidad de dominar el pino.",
    ojo: "Dejar caer la cadera y arquear la espalda. El core sostiene la línea, no la espalda baja.",
  },

  // -- Avanzado --------------------------------------------------------------
  {
    id: "snatch",
    nombre: "Snatch (arranque)",
    nivel: "AVANZADO",
    categoria: "Levantamiento",
    como: "Del piso a por encima de la cabeza en un solo movimiento, con agarre ancho y recepción en sentadilla.",
    para: "El movimiento más técnico y más rápido del deporte. Bien hecho, es el mejor entrenador de potencia que existe.",
    ojo: "No es para aprender por app ni con fatiga. Si la barra se va adelante o el hombro no bloquea, ese peso todavía no es tuyo.",
  },
  {
    id: "muscle_up",
    nombre: "Muscle-up",
    nivel: "AVANZADO",
    categoria: "Gimnásticos",
    como: "Dominada alta con transición de pecho sobre la barra o anillas, y termina en fondo con brazos bloqueados.",
    para: "La puerta de entrada a los WOD avanzados; junta tirón y empuje en una repetición.",
    ojo: "Intentarlo sin dominar la transición en anillas bajas. El hombro y el codo son los que se llevan la mala transición.",
  },
  {
    id: "handstand_push_up",
    nombre: "Flexión en el pino",
    nivel: "AVANZADO",
    categoria: "Gimnásticos",
    como: "Contra la pared, baja hasta tocar la cabeza en un punto marcado y empuja hasta bloquear brazos.",
    para: "El empuje vertical más exigente sin barra, y de los que más rápido se degrada con fatiga.",
    ojo: "Bajar sin control. Escala con déficit de altura o con banda antes que arriesgar el cuello.",
  },
  {
    id: "squat_clean",
    nombre: "Squat clean",
    nivel: "AVANZADO",
    categoria: "Levantamiento",
    como: "Clean recibido en sentadilla frontal completa, subiendo desde abajo con la barra en los hombros.",
    para: "Mueve más peso que el power clean porque te metes debajo de la barra en vez de esperarla arriba.",
    ojo: "Recibir con los codos bajos en el fondo. Ahí la barra rueda y no hay forma de salvar la repetición.",
  },
  {
    id: "ghd",
    nombre: "GHD sit-up",
    nivel: "AVANZADO",
    categoria: "Acondicionamiento",
    como: "En el aparato de glúteo-isquios, extensión y flexión completa del tronco con control en los dos sentidos.",
    para: "Trabaja el core en un rango que ningún abdominal alcanza.",
    ojo: "Hacer volumen alto sin adaptación previa. Es el movimiento con más casos documentados de rabdomiólisis del deporte: se entra con pocas repeticiones y se sube despacio.",
  },
];
